//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudyCorner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignment
    {
        public int assignID { get; set; }
        public string assignDATE { get; set; }
        public string assignName { get; set; }
        public string fileName { get; set; }
        public Nullable<int> NoQues { get; set; }
        public Nullable<System.DateTime> addedON { get; set; }
    }
}
