//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudyCorner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enquiry
    {
        public int enquiryid { get; set; }
        public string name { get; set; }
        public string emailId { get; set; }
        public string mobno { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> enquiry_dt { get; set; }
    }
}
