//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudyCorner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public string BookName { get; set; }
        public string BookWriter { get; set; }
        public Nullable<System.DateTime> AddedON { get; set; }
        public string BookFileName { get; set; }
    }
}
