//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudyCorner.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstudyCornerEntities : DbContext
    {
        public EstudyCornerEntities()
            : base("name=EstudyCornerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<enquiry> enquiries { get; set; }
        public DbSet<login> logins { get; set; }
        public DbSet<notification> notifications { get; set; }
        public DbSet<registration> registrations { get; set; }
        public DbSet<StdFeedback> StdFeedbacks { get; set; }
        public DbSet<DAnswer> DAnswers { get; set; }
        public DbSet<Dquestion> Dquestions { get; set; }
        public DbSet<StdUpload> StdUploads { get; set; }
        public DbSet<assignment> assignments { get; set; }
        public DbSet<StudyMaterial> StudyMaterials { get; set; }
        public DbSet<Library> Libraries { get; set; }
        public DbSet<Softupload> Softuploads { get; set; }
        public DbSet<LeaveApp> LeaveApps { get; set; }
    }
}
