//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudyCorner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public registration()
        {
            this.StdFeedbacks = new HashSet<StdFeedback>();
            this.DAnswers = new HashSet<DAnswer>();
            this.Dquestions = new HashSet<Dquestion>();
            this.StdUploads = new HashSet<StdUpload>();
            this.LeaveApps = new HashSet<LeaveApp>();
        }
    
        public int Sn { get; set; }
        public string name { get; set; }
        public string Fname { get; set; }
        public string college { get; set; }
        public string Qualification { get; set; }
        public string branch { get; set; }
        public Nullable<int> course_year { get; set; }
        public string training_name { get; set; }
        public string emailID { get; set; }
        public string mobno { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
        public string picName { get; set; }
        public string pass { get; set; }
        public Nullable<System.DateTime> regDate { get; set; }
    
        public virtual ICollection<StdFeedback> StdFeedbacks { get; set; }
        public virtual ICollection<DAnswer> DAnswers { get; set; }
        public virtual ICollection<Dquestion> Dquestions { get; set; }
        public virtual ICollection<StdUpload> StdUploads { get; set; }
        public virtual ICollection<LeaveApp> LeaveApps { get; set; }
    }
}
