//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudyCorner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Softupload
    {
        public int SerialNo { get; set; }
        public Nullable<System.DateTime> softDate { get; set; }
        public string SoftName { get; set; }
        public string SoftFile { get; set; }
    }
}
