//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudyCorner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyMaterial
    {
        public int StdMatID { get; set; }
        public string title { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> AddedON { get; set; }
    }
}
